authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"
urlpatterns = [
    path("signup/", views.SignUp, name="signup"),
    path("login/", views.Login, name="login"),
    path("logout/", views.Logout, name="logout"),
    path("", views.HomePage.as_view(), name="home"),
    path("profile/", views.ProfileUpdate, name="profile"),
    path("settings/", views.settings, name="settings"),
]

qr_gen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("qr_gen/", include("qr_gen_app.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
    # path("", include("qr_gen_app.urls")),

'''

# ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL,
#                               document_root=settings.MEDIA_ROOT)

# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

qr_gen_app/urls.py
from django.urls import path, include
from . import views


app_name = 'qr_gen_app'

urlpatterns = [
    path("qr_dashboard/",views.qr_dashboardview.as_view(), name='qr_dashboard'),
    path("qr_dashboard3/",views.QrcodeBusinessView, name='qr_dashboard3'),
    path("qr_dashboard4/",views.QrcodeAppDownloadView, name='qr_dashboard4'),
    path("qr_dashboard5/",views.QrcodeEventView, name='qr_dashboard5'),
    path("business_code/", views.business_qrcode_view, name='business_code'),
    path("app_code/", views.app_qrcode_view, name='app_code'),
    path("event_code/", views.event_qrcode_view, name='event_code'),

]
    

qrc_proj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
  
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
# from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from .managers import MyUserManager

"""
- this model will allow user to have access_token and email will be a require field
- use the email and password instead of username and password
"""


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = MyUserManager()

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, max_length=120, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, null=True)
    phone_Number = models.CharField(max_length=120, null=True)
    avatar = models.ImageField(null=True, default="avatar.svg")
    website_url = models.URLField(null=True)
    url = models.URLField(null=True)
    bio = models.TextField(null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

authentication/forms.py
"""
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.forms import ModelForm
from .models import Profile
>>>>>>> auth


class UserForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["avater", "name", "email", "phone_Number", "bio"]
"""

authentication/views.py
from re import template
from django.contrib.auth.decorators import login_required
from django.utils.safestring import mark_safe
from .models import CustomUser
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
from django.http import HttpResponse
from django.contrib import messages
from .models import Profile

# from .forms import UserForm
from django.views.generic import TemplateView

User = CustomUser
# Create your views here.
def SignUp(request):
    template_name = "authentication/registration.html"
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        password = request.POST.get("password")
        cnfrm_password = request.POST.get("cnfrm_password")
        if password != cnfrm_password:
            messages.warning(request, "Passwords do not match!")

        if User.objects.filter(email=email).exists():
            messages.info(request, "Email already exists")
            return redirect("authentication:signup")

        user = User.objects.create_user(email=email, password=password)
        user.set_password(password)
        user.save()
        login(request, user)
        return redirect("authentication:profile")
    return render(request, template_name)


def Login(request):
    if request.user.is_authenticated:
        messages.info(
            request,
            mark_safe(f"You are already logged in as <b>{request.user.email}</b>."),
        )
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(request, username=email, password=password)
        if user:
            login(request, user)
            messages.success(request, f"{user.email} logged in successfully!")
            return redirect("qr_gen_app:qr_dashboard")
        else:
            messages.warning(request, "Please check your credentials")
    return render(request, "authentication/login.html")


def Logout(request):
    if request.method == "POST":
        messages.INFO(request, "You have logged out successfully!")
        logout(request)
    return redirect("authentication:home")



class HomePage(TemplateView):
    template_name = "authentication/index.html"


@login_required(login_url="login")
def ProfileUpdate(request):
    template_name = "authentication/dashboard-signup.html"
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        phone_Number = request.POST.get("phoneNo")
        #we'll modify the avater later
        avatar = request.FILES.get("avatar")
        bio = request.POST.get("bio")
        url = request.POST.get("url")
        website_url = request.POST.get("website-url")

        profile = Profile.objects.create(user=request.user,
        name=name, 
        phone_Number=phone_Number,
        avatar=avatar,
        bio=bio, 
        url=url,
        website_url=website_url)
        profile.save()
        messages.success(request, "Welcome,You can now Generate QR ")
        return redirect("qr_gen_app:qr_dashboard")

    return render(request, template_name)

@login_required(login_url="login")
def settings(request):
    template_name= "authentication/settings.html"
    return render(request, template_name)

authentication/templates/authentication/dashboard-signup.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% comment %} <link rel="stylesheet" href="{% static '/styles/dashboard-signup.css' %}" /> {% endcomment %}
    <title>Dashboard Profile</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{% static './styles/dashboard-signup.css' %}"
    />

    <script
      src="https://kit.fontawesome.com/cf2b35cc7f.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body>
    <main class="container">
      <form class="row" method="POST">
        {% csrf_token %}
        <section class="bg-white rounded my-3 col-lg-6">
          <div class="background-img rounded"></div>
          <div class="profile-img">
            <img
              src="https://randomuser.me/api/portraits/lego/2.jpg"
              alt="rand"
            />
          </div>
          <div class="p-3">
            <h4>Personal Details</h4>
            <div class="form-row">
              <div class="form-group spacing">
                <label for="fullname">Full name</label>
                <input type="text" id="fullname" placeholder="Jane Doe" name="name" required />
              </div>
            </div>
            <div class="form-row">
              <div class="form-group">
                <label for="email">Email Address</label>
                <input
                  type="email"
                  name="email"
                  id="email"
                  placeholder="johndoe@gmail.com"
                  required
                />
              </div>
            </div>
            <div class="form-row">
              <div class="form-group">
                <label for="phoneNo">Phone Number</label>
                <input type="text" name="phoneNo" id="phoneNo" minlength="10" maxlength="13" placeholder="+23490909990" required />
              </div>
            </div>
            <div class="form-row">
              <div class="form-group">
                <textarea
                  id="txtid"
                  name="txtname"
                  rows="4"
                  cols="50"
                  name="bio"
                  placeholder="Short bio"
                  maxlength="200"
                >
                </textarea>
              </div>
            </div>
          </div>
        </section>
        <section class="col-lg-6">
          <div class="bg-white rounded p-3 my-3">
            <h4>Website Profile</h4>
            <div class="form-row">
              <div class="form-group spacing d-flex">
                <input
                  class="w-25 m-2"
                  type="text"
                  name="website"
                  placeholder="Behance"
                  disabled
                />
                <input
                  class="w-75 m-2"
                  type="text"
                  id="URL"
                  name="url"
                  placeholder="URL"
                />
              </div>
            </div>
            <div class="form-row">
              <div class="form-group">
                <input
                  type="text"
                  class="m-2"
                  id="website-URL"
                  name="website-URL"
                  placeholder="Website URL"
                />
              </div>
            </div>
          </div>
          <div class="bg-white rounded p-3 my-3">
            <h4>Social Media Info</h4>
            <div class="form-row">
              <div class="form-group spacing d-flex">
                <select class="w-25">
                  <option>Twitter</option>
                  <option>Facebook</option>
                  <option>Instagram</option>
                </select>
                <input
                  class="w-75 m-2"
                  type="text"
                  id="URL"
                  placeholder="URL"
                />
              </div>
            </div>
          </div>
          <div class="w-100">
            <button
              class="btn purple-button my-2 px-4 w-100"
              href="{% url 'qr_gen_app:qr_dashboard' %}"
              role="button"
            >
              Create a Profile
            </button>
          </div>
        </section>
      </form>
    </main>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

{% endblock content %}

authentication/templates/authentication/login.html
{% load static %}
<html lang="en">
  <head>
    <title>GenOR Login</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="{% static './styles/login.css' %}" />
    <style>
      .warning{
        color: red;
        font-style: italic;
        padding: .5rem;
        margin-bottom: .5rem;
        background-color: #ff000017;
        border-radius: .75rem;
      }
    </style>

  </head>
  <body>
    <main>
      <div class="container">
        <div id="login-img">
          <div>
            <div class="spacing">
              <img src="{% static './images/qrcode 2.png' %}" />
            </div>
            <div id="qr-img-div" class="spacing animated">
              <img id="qr-img" src="{% static './images/amico.png' %}" />
            </div>
            <div class="img-text">
              <h2 class="spacing">Welcome</h2>
              <p class="spacing">
                Log into GenQr to activate and have easy and well defined
                accessibility to different features...
              </p>
            </div>
          </div>
        </div>
        <form method="POST">
          {% if messages %}
            <div class="warning">
              {% for message in messages %}
              <p>{{ message }}</p>
              {% endfor %}   
            </div>
          {% endif %}

          {% csrf_token %}
          <div class="second-genqr-img spacing">
            <img src="{% static './images/qrcode 2.png' %}" />
          </div>
          <h2 id="sign">Welcome Back...</h2>
          <p>Please enter your Username and Password</p>
          <div class="form-row">
            <div class="form-group spacing">
              <label for="firstname">Username</label>
              <input
                type="text"
                id="username"
                name="email"
                placeholder="........@gmail.com"
                required
              />
            </div>
          </div>
          <div class="form-row">
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" name="password" id="password" minlength="6" required />
            </div>
          </div>
          <small class="text-light-purple">Forgot password?</small>
          <div id="button">
            <button>Login</button>
          </div>
          <small class="spacing"
            >Don't have an account?
            <span class="text-light-purple">
              <a href="{% url 'authentication:signup' %}">Sign up</a> </span
            ></small
          >
        </form>
      </div>
    </main>
  </body>
</html>

authentication/templates/authentication/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Signup page</title>
    <link rel="stylesheet" href="{% static './styles/signup.css' %}" />
    <!-- <link rel="stylesheet" href="script.js" /> -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600&display=swap"
      rel="stylesheet"
    />
    />
  </head>
  {% block content %}
  <body>
    <section class="leftside">
      <div class="logo">
        <img class="logo" src=" {% static './images/qrcode 2.png' %}" alt="" />
      </div>
      <img
        class="heroimg"
        src="{% static './images/amico.png' %}"
        alt="frontimg"
      />
      <h2>Welcome</h2>
      <p>
        Sign up into GenQr to activate and have easy and well defined
        accessibility to different features
      </p>
    </section>
    <main>
      <h2 class="left">Create Account</h2>
      <form class="signup" method="POST" action="">
        {% csrf_token %}
        <label for="name">Name</label>
        <input type="text" name="name" placeholder="John Doe" required />
        <label for="email">Email</label>
        <input
          type="email"
          name="email"
          placeholder="....@gmail.com"
          required
        />
        <label for="Password">Password</label>
        <input
          type="password"
          name="password"
          placeholder="********"
          minlength="6"
          required
        />
        <label for=" Confirm Password">Confirm Password</label>
        <input
          type="password"
          name="cnfrm_password"
          placeholder="********"
          minlength="6"
          required
        />

        <button><a href="{% url 'authentication:home' %}"></a>Sign Up</button>
      </form>

      <form class="box" action="">
        <input type="checkbox" />
        <label for="">By using this , you agree to the term of users</label>
      </form>
      <div class="end">
        <p>
          You already have an account?
          <a href="{% url 'authentication:login' %}">LOGIN</a>
        </p>
      </div>
    </main>
  </body>
  {% endblock %}
</html>

authentication/templates/authentication/settings.html
{% extends "base.html" %}

{% load static %}

{% block content %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static '/styles/settings.css' %}">
</head>

<body>


    <div class="settings-container">

        <div class="info">
            <h2 class="info-h3">personal information</h2>
            <p>This is information will be displayed when your qr code is scanned.</p>
        </div>


        <div class="user-detail">
            <div class="pro-img">
                <img src="{% static './images/default-user-icon-8.jpg' %}" alt="profile image" srcset="">
            </div>
            <div class="ceo-text">
                <h2>Constance Jane</h2>
                <p class="para-text">constancejanedoi@gmail.com</p>
                <p>CEO of Lorren org.</p>
                <p>Florida, USA</p>
            </div>
        </div>



        <form action="">
            <div class="my-name">
                <div>
                    <label for="firstname" class="fname">First Name</label>
                    <input class="text" type="text" name="firstname" placeholder="Jane Doe" id="fname">
                </div>
                <div>
                    <label for="Lname">Last Name</label>
                    <input type="text" id="Lname" name="lastname" placeholder="Jane Doe" id="Lname">
                </div>
            </div>
            <div class="my-name">
                <div>
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" placeholder="password">
                </div>
                <div>
                    <label for="email" class="email">Email</label>
                    <input class="email" type="email" name="email" placeholder="@gmail.com" id="email">
                </div>
            </div>
            <div class="my-name">
                <div><label for="organization name">Organization Name</label>
                    <input type="text" id="organization name" name="organization name" placeholder="Lorren Org"
                        id="organization name">
                </div>
                <div>
                    <label for="phone">Phone Number</label>
                    <input type="phone" id="phone Number" name="phone Number" placeholder="+2349095749888">
                </div>
            </div>
            <div class="my-name">
                <div>
                    <label for="organization email">Organization Email</label>
                    <input type="email" id="organization email" name="organization email" placeholder="@gmail.com"
                        id="organization email">
                </div>
                <div>
                    <label for="Country">Country</label>
                    <input type="text" id="country" name="country" placeholder="Nigeria">
                </div>
            </div>
            <a href="{% url 'qr_gen_app:qr_dashboard' %}"><button type="submit" class="right">Save</button></a>

        </form>


           
    </div>

</body>

</html>
{% endblock content %}