qr_gen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("qr_gen/", include("qr_gen_app.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
    # path("", include("qr_gen_app.urls")),

'''

# ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL,
#                               document_root=settings.MEDIA_ROOT)

# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

qr_gen_app/urls.py
from django.urls import path, include
from . import views


app_name = 'qr_gen_app'

urlpatterns = [
    path("qr_dashboard/",views.qr_dashboardview.as_view(), name='qr_dashboard'),
    path("qr_dashboard3/",views.QrcodeBusinessView, name='qr_dashboard3'),
    path("qr_dashboard4/",views.QrcodeAppDownloadView, name='qr_dashboard4'),
    path("qr_dashboard5/",views.QrcodeEventView, name='qr_dashboard5'),
    path("business_code/", views.business_qrcode_view, name='business_code'),
    path("app_code/", views.app_qrcode_view, name='app_code'),
    path("event_code/", views.event_qrcode_view, name='event_code'),

]
    

qrc_proj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
  
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qr_gen_app/models.py
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image
from authentication.models import CustomUser



class BaseModel(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    qr_code = models.ImageField(upload_to="qr_codes", blank=True)

    class Meta:
        abstract = True


    def save(self, *args, **kwargs):
        qrcode_img = qrcode.make(self.name)
        canvas = Image.new("RGB", qrcode_img.size, "white")
        canvas.paste(qrcode_img)
        fname = f"qr_code-{self.id}-{self.created_at}.png"
        buffer = BytesIO()
        canvas.save(buffer, "PNG")
        self.qr_code.save(fname, File(buffer), save=False)
        canvas.close()
        super().save(*args, **kwargs)


# For business card
class QrcodeBusiness(BaseModel):
   
    company = models.CharField(max_length=200)
    about = models.TextField()
    opening_hours = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    email = models.EmailField(max_length=254, null=True)
    phone = models.CharField(max_length=12, null=True)
    #url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return str(self.company)



# For App Download
class QrcodeAppDownload(BaseModel):
    app_name = models.CharField(max_length=200)
    description = models.TextField()
    #url = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.app_name)

    

# Event
class QrcodeEvent(BaseModel):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    organizer = models.CharField(max_length=200)
    about = models.TextField()
    event_name = models.CharField(max_length=200)
    venue = models.CharField(max_length=200, null=True)
    organizer_email = models.EmailField(max_length=254, null=True)
    organizer_phone = models.CharField(max_length=12, null=True)
   

    def __str__(self):
        return str(self.event_name)

qr_gen_app/views.py
from nturl2path import url2pathname
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .models import QrcodeBusiness, QrcodeAppDownload, QrcodeEvent
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView




# user = BaseModel
class qr_dashboardview(TemplateView):
    template_name = "qr_gen_app/maindashboard.html"

#functions to generate qr codes
@login_required
def QrcodeBusinessView(request):
    if request.method =='POST':
        company= request.POST.get('company', None)
        about = request.POST.get('about', None)
        opening_hours = request.POST.get('opening_hours', None)
        address = request.POST.get('address', None)
        email = request.POST.get('email', None)
        phone = request.POST.get('phoneNo', None)
        url = request.POST.get('websiteURL', None)
        business = QrcodeBusiness(user=request.user,
        company=company, 
        about=about,
        opening_hours=opening_hours,
        address=address,
        email=email,
        phone=phone,
        name=url)
        business.save()
        
        #messages.success(request, 'Business Card Created Successfully')
        return redirect ('qr_gen_app:business_code')
    return render(request, 'qr_gen_app/dashboard3.html')

    
@login_required
def QrcodeAppDownloadView(request):
    if request.method =='POST':
        app_name = request.POST.get('app_name', None)
        description = request.POST.get('description', None)
        url= request.POST.get('url', None)
        appdownload = QrcodeAppDownload(user=request.user,
        app_name=app_name, 
        description=description,
        name=url,
        )
        appdownload.save()
        
        #messages.success(request, 'App Download Created Successfully')
        return redirect ('qr_gen_app:app_code')

    return render(request, 'qr_gen_app/dashboard4.html')


@login_required
def QrcodeEventView(request):
    if request.method =='POST':
        organizer = request.POST.get('organizer', None)
        about = request.POST.get('about', None)
        event_name = request.POST.get('event_name', None)
        venue = request.POST.get('venue', None)
        organizer_email = request.POST.get('organizer_email', None)
        organizer_phone = request.POST.get('organizer_phone', None)
        event = QrcodeEvent(user=request.user,
        organizer=organizer,
        about=about,
        event_name=event_name,
        venue=venue,
        organizer_email=organizer_email,
        organizer_phone=organizer_phone,
        name=(f"Organizer: {organizer} \nAbout: {about} \nEvent: {event_name} \nVenue: {venue} \nOrganizer's Email: {organizer_email} \nOrganizer's Phone number: {organizer_phone} "))
        event.save()
        #messages.success(request, 'Event Created Successfully')
        return redirect ('qr_gen_app:event_code')

    return render(request, 'qr_gen_app/dashboard5.html')

#functions to return qr codes to the screen
def business_qrcode_view(request):
    obj = QrcodeBusiness.objects.order_by('-id')[0]

    return render (request, 'qr_gen_app/qrcode_view.html', {'obj':obj})

def app_qrcode_view(request):
    obj = QrcodeAppDownload.objects.order_by('-id')[0]
    return render (request, 'qr_gen_app/qrcode_view.html', {'obj':obj})

def event_qrcode_view(request):
    obj = QrcodeEvent.objects.order_by('-id')[0]
    return render (request, 'qr_gen_app/qrcode_view.html', {'obj':obj})

qr_gen_app/templates/qr_gen_app/dashboard4.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="">
    <title>Gen QR</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static './styles/dashboard4.css' %}">
</head>

<body>
    <main class="container dashboard4">
        <ul class="navbar-nav ms-auto my-2 my-lg-0 d-flex flex-row">
            <li class="nav-item mx-2">
              <a class="nav-link" href="{% url 'qr_gen_app:qr_dashboard3' %}">Business Card</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link active" href="{% url 'qr_gen_app:qr_dashboard4' %}">App Download</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link" href="{% url 'qr_gen_app:qr_dashboard5' %}">Event Invite</a>
            </li>
        </ul>
        <form class="row" method="POST">
            {% csrf_token %}
            <section class="rounded my-3 col-md-6 col-lg-6">
                <div class="bg-white p-3">
                    <div class="accordion p-2 rounded" id="accordionExample">
                        <div class="accordion-item border-0">
                            <h2 class="accordion-header" id="headingOne">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Basic Info
                                </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                                data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <div class="form-row">
                                        <div class="form-group spacing">
                                            <label for="appName">App Name</label>
                                            <input name="app_name" type="text" id="appName" placeholder="e.g Jumia" required>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group">
                                            <label for="description">Description</label>
                                            <input name="description" type="text" id="description" placeholder="E-commerce" required>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item border-0">
                            <h2 class="accordion-header" id="headingTwo">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                                    App Links
                                </button>
                            </h2>
                            <div id="collapseTwo" class="accordion-collapse collapse show" aria-labelledby="headingTwo"
                                data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <div class="form-row">
                                        <div class="form-group spacing">
                                            <label for="androidApp">Android/ios App</label>
                                            <input name="url" type="text" id="url" placeholder="https://....">
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        {% comment %} <div class="form-group">
                                            <label for="iosApp">iOS App</label>
                                            <input name="iosApp_link" type="text" id="iosApp" placeholder="https://apps.apple.com/us/app....">
                                        </div> {% endcomment %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item border-0">
                            <h2 class="accordion-header" id="headingThree">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                                    Add Logo
                                </button>
                            </h2>
                            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
                                data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <div class="form-row">
                                        <div class="form-group row spacing d-flex align-items-baseline gap-4">
                                            <div class="purple-dotted-div text-center d-flex col-lg-6"
                                                id="img-preview-panel">
                                                <span class="m-auto text-center plus-button">+</span>
                                            </div>
                                            <div class="col-lg-6">
                                                <span class="img-warn">Note : Your file size should not exceed 2mb</span><br />
                                                <label for="imgInp" class="btn add-button">Add Image</label>
                                                <input accept="image/*" type='file' name="file"
                                                    style="visibility:hidden;" id="imgInp" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="col-md-6 my-3 col-lg-4">
                <div class="bg-white p-3">
                    <h4>QR code section</h4>
                    <div>
                        <div class="purple-dotted-QRdiv m-auto">
                            <img src="{% static './images/sample-qr.png' %}" class="img-fluid" alt="sample-qr" />
                        </div>
                    </div>
                    <div class="accordion p-2 rounded" id="accordionQRExample">
                        <div class="accordion-item border-0">
                            <h2 class="accordion-header" id="headingQROne">
                                <button class="accordion-button" type="button" data-bs-toggle=""
                                    data-bs-target="#collapseQROne" aria-expanded="" aria-controls="">
                                    Shape
                                </button>
                            </h2>
                            <div id="collapseQROne" class="accordion-collapse collapse"
                                aria-labelledby="headingQROne" data-bs-parent="#accordionQRExample">
                                <div class="accordion-body">
                                    <div class="form-row">
                                        <h3>Code for QR shape here</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item border-0">
                            <h2 class="accordion-header" id="headingQRThree">
                                <button class="accordion-button" type="button" data-bs-toggle=""
                                    data-bs-target="#collapseQRThree" aria-expanded="true"
                                    aria-controls="collapseQRThree">
                                    Add image/logo
                                </button>
                            </h2>
                            <div id="collapseQRThree" class="accordion-collapse collapse"
                                aria-labelledby="headingQRThree" data-bs-parent="#accordionQRExample">
                                <div class="accordion-body">
                                    <div class="form-row">
                                        <h3>Code for QR image here</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item border-0">
                            <h2 class="accordion-header" id="headingQRTwo">
                                <button class="accordion-button" type="button" data-bs-toggle=""
                                    data-bs-target="#collapseQRTwo" aria-expanded="true" aria-controls="collapseQRTwo">
                                    Color
                                </button>
                            </h2>
                            <div id="collapseQRTwo" class="accordion-collapse collapse" aria-labelledby="headingQRTwo"
                                data-bs-parent="#accordionQRExample">
                                <div class="accordion-body">
                                    <div class="form-row">
                                        <h3>Code for QR color here</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="buttons-for-QRcode">
                        <div class="d-flex justify-content-around">
                            <button class="btn white-button my-2 px-3" role="button">Download QR</button>
                            <button class="btn purple-button my-2 px-3" role="button">Generate code</button>
                        </div>
                    </div>
                </div>
            </section>
        </form>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>
    <script>
        const fReader = new FileReader();
        const imgUpload = document.getElementById("imgInp");
        const imgPreviewPanel = document.getElementById("img-preview-panel");
        let imgPreviewHtml = ""

        imgUpload.addEventListener('input', (e) => {
            console.log(e.target.files[0])
            fReader.readAsDataURL(e.target.files[0]);
            fReader.onloadend = function (event) {
                console.log(event.target.result)
                imgPreviewHtml += `
    <img class="m-2" width="149px" height="168px" src=${event.target.result} />
    `

                imgPreviewPanel.innerHTML = imgPreviewHtml
            }
        })
    </script>
</body>

</html>
{% endblock content %}

qr_gen_app/templates/qr_gen_app/maindashboard.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href=" {% static '/styles/maindashboard.css' %}">
</head>
<body>
    <div class="activity-container">

        <div class="qr-profile">

            <div class="img-code">
                <div class="code-image">
                    <img src="{% static '/images/mainqr.png' %}" alt="qr-code image">
                </div>
                <div  class="cta-section">
                    <p class="cta-text">Sorry you do not have any active QR code. Generate one to see it active.</p>
                    <a href="{% url 'qr_gen_app:qr_dashboard3' %}"><button class="cta-btn" type="submit">Generate code</button></a>

                </div>
            </div>

            <div class="codes-data">
                <h4>QR codes</h4>
                <p>There are no available qr codes now</p>
            </div>

        </div>


        <div class="qr-overview">
            
            <div class="overview-heading">
                <h4>Overview</h4>
            </div>

            <div class="track-container">

                <div class="tracker-wrapper">
                    <div class="tracker">
                        <div class="track-code">
                            <img src=" {% static '/images/code-sm.png' %} " alt="" srcset="">
                        </div>
                        <div>
                            <p style="font-size: 36px; font-weight:600; ">0</p>
                            <p style="font-weight:500; ">Total QR codes</p>
                        </div>
                        <img class="arrow" src="{% static '/images/arrow-right.png' %}" alt="">
                    </div>

                    <div class="tracker">
                        <div class="track-code">
                            <img src=" {% static '/images/archive.png' %} " alt="" srcset="">
                        </div>
                        <div>
                            <p style="font-size: 36px; font-weight:600; ">0</p>
                            <p style="font-weight:500; ">Archived QR codes</p>
                        </div>
                        <img class="arrow"  src="{% static '/images/arrow-right.png' %}" alt="">
                    </div>
                </div>
                <div class="tracker-wrapper">

                    <div class="tracker">
                        <div class="track-code">
                            <img src="{% static '/images/active.png' %}" alt="" srcset="">
                        </div>
                        <div>
                            <p style="font-size: 36px; font-weight:600; ">0</p>
                            <p style="font-weight:500; ">Active QR codes</p>
                        </div>
                        <img class="arrow"  src="{% static '/images/arrow-right.png' %}" alt="">
                    </div>

                    <div class="tracker">
                        <div class="track-code">
                            <img src="{% static '/images/Vector.png' %}" alt="" srcset="">
                        </div>
                        <div>
                            <p style="font-size: 36px; font-weight:600; ">0</p>
                            <p style="font-weight:500; ">Closed QR codes</p>
                        </div>
                        <img class="arrow"  src="{% static '/images/arrow-right.png' %}" alt="">
                    </div>

                </div>
            </div>


        </div>





    </div>
    
</body>
</html>
{% endblock content %}

qr_gen_app/templates/qr_gen_app/qrcode_view.html
{% extends 'base.html' %}

{% load static%}

{% block content %}
<!DOCTYPE html>
{% load social_share %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/qrcode_view.css' %}" />
  </head>
  <body>
    <main style="text-align:center">
      <h1>Here is your QR code</h1>
      <!--<h2>{{obj.Qrcode_name.}}</h2>-->
     
      <img src={{obj.qr_code.url}}>
    
 
     
      {% post_to_facebook obj.qr_code.url "Share to Facebook!" %}
      {% post_to_linkedin obj.qr_code.url "Share to Linkedin!" %}
      {% post_to_telegram obj.qr_code.url "Share to Telegram!" %}
      {% post_to_twitter obj.qr_code.url "Share to Twitter!" %}
      {% post_to_whatsapp obj.qr_code.url "Share to Whatsapp!" %}

      <h5>Right click on the image and click save to download to your devices</h5>
      
    </main>
  </body>
</html>


    {% endblock content %}